### ISSUE TITLE
Strong name assemblies

### ISSUE THREAD

**Issue by iadonkey** [meziantou/Meziantou.Framework#564] opened 2023-10-04 20:04 UTC
We are building a vsix extensions and need strong names for our assemblies and its dependencies.
At least Meziantou.Framework.CredentialManager 1.4.2 doesn't have [a strong name assembly](https://learn.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name) so for now we had to switch to https://github.com/AdysTech/CredentialManager for this reason.

Maybe others have a similar issue, so I just wanted to let you know about this issue

**Comment by meziantou** [comment] 2023-10-04 20:09
Duplicate of https://github.com/meziantou/Meziantou.Framework/issues/487.

Summary: You can use [StrongNamer](https://github.com/dsplaisted/strongnamer) as mentioned in [this comment](https://github.com/meziantou/Meziantou.Framework/issues/487#issuecomment-1468997943) to automatically add strong name to all your dependencies.

**Comment by iadonkey** [comment] 2023-10-04 20:09
Just found it myself, sorry for the duplicate

**Closed by meziantou** 2023-10-04 20:09 UTC
